import { Command } from 'commander';
import {generateAddressService} from './service/generated-address-service.js'; // Update the path

const program = new Command();

program.command('ga')
    .option('--n <number>', 'A number of wallets will be generated By the number', '10')
    .option('--path <string>', 'the path where you want to save the Excel fil', './')
    .action((options) => {
        generateAddressService(options.n, options.path)
    })

program.parse();